import json

from groq import Groq

from services.analytics_service import (
    get_total_orders,
    get_total_revenue,
    get_average_order_value,
    get_total_items_sold,
    get_top_selling_items,
    get_alcohol_order_split,
    get_vegetarian_split,
    get_recent_orders,
    get_revenue_by_date,
)


def get_groq_client():

    import streamlit as st

    api_key = st.secrets.get(
        "GROQ_API_KEY",
        "",
    )

    if not api_key:
        raise ValueError(
            "GROQ_API_KEY is not configured."
        )

    return Groq(
        api_key=api_key
    )


def build_manager_data():

    return {
        "total_orders": get_total_orders(),

        "total_revenue": get_total_revenue(),

        "average_order_value": (
            get_average_order_value()
        ),

        "total_items_sold": (
            get_total_items_sold()
        ),

        "top_selling_items": (
            get_top_selling_items(
                limit=10
            )
        ),

        "alcohol_order_split": (
            get_alcohol_order_split()
        ),

        "vegetarian_split": (
            get_vegetarian_split()
        ),

        "revenue_by_date": (
            get_revenue_by_date()
        ),

        "recent_orders": (
            get_recent_orders(
                limit=10
            )
        ),
    }


def build_manager_prompt(data):

    return f"""
You are an AI restaurant management analyst
for a fictional restaurant called UrbanBite.

You are analyzing real order and revenue data
generated by the OrderIQ restaurant ordering system.

Your job is to convert the supplied business data
into useful, practical management insights.

IMPORTANT RULES:

1. Do NOT invent numbers.
2. Do NOT invent customers.
3. Do NOT invent menu items.
4. Do NOT assume trends that cannot be supported by the data.
5. Clearly acknowledge when the dataset is small.
6. Do not calculate a number that is not supported
   by the supplied data.
7. Focus on actionable restaurant-management decisions.
8. Keep recommendations realistic for a restaurant manager.
9. Do not recommend changing prices unless the data
   provides enough evidence.
10. Do not make unsupported inventory recommendations.

Return ONLY valid JSON.

Required JSON structure:

{{
    "executive_summary": "2-3 sentence summary",
    "key_observations": [
        "Observation 1",
        "Observation 2",
        "Observation 3"
    ],
    "recommendations": [
        {{
            "action": "Recommended action",
            "reason": "Why this action makes sense"
        }},
        {{
            "action": "Recommended action",
            "reason": "Why this action makes sense"
        }},
        {{
            "action": "Recommended action",
            "reason": "Why this action makes sense"
        }}
    ],
    "data_caveat": "Important limitation of the current dataset"
}}

BUSINESS DATA:

{json.dumps(data, indent=2, ensure_ascii=False)}
"""


def extract_json(response_text):

    response_text = response_text.strip()

    if response_text.startswith("```"):

        lines = response_text.splitlines()

        lines = [
            line
            for line in lines
            if not line.strip().startswith("```")
        ]

        response_text = "\n".join(lines).strip()

    start = response_text.find("{")

    end = response_text.rfind("}")

    if start == -1 or end == -1:

        raise ValueError(
            "AI did not return valid JSON."
        )

    json_text = response_text[
        start:end + 1
    ]

    return json.loads(
        json_text
    )


def generate_manager_insights():

    data = build_manager_data()

    client = get_groq_client()

    prompt = build_manager_prompt(
        data
    )

    response = client.chat.completions.create(

        model="openai/gpt-oss-20b",

        messages=[
            {
                "role": "system",
                "content": (
                    "You are a precise restaurant "
                    "business analyst. Return only JSON."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],

        temperature=0,

        max_tokens=1200,
    )

    response_text = (
        response.choices[0]
        .message
        .content
    )

    return extract_json(
        response_text
    )